---
- name: Install the version '1.16.2' of package "consul"
  get_url:
    url: wget https://releases.hashicorp.com/consul/1.16.2/consul_1.16.2_linux_amd64.zip
    dest: /usr/local/bin

- name: Extract consul_1.16.2_linux_amd64.zip into consul
  unarchive:
    src: /usr/local/bin/consul_1.16.2_linux_amd64.zip
    dest: /usr/local/bin/consul
    mode: '770'

- 