- name: Install consul client
  hosts: all
  tasks:
    - name: Install unzip
      apt:
        name: unzip
    - name: Install and unarchive consul
      unarchive:
        src: https://releases.hashicorp.com/consul/1.16.2/consul_1.16.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: '755'
    - name: Create /etc/consul.d directory if it does not exist
      file:
        path: /etc/consul.d
        state: directory
        mode: '644'
    - name: Copy consul configures files
      copy:
        src: ../configures/consul-client.json
        dest: /etc/consul.d/consul.json
        mode: '755'
    - name: Copy consul systemd file
      copy:
        src: ../configures/consul-client.service
        dest: /lib/systemd/system/consul.service
        owner: root
        group: root
        mode: '644'
      notify: Start consul
  handlers:
    - name: Start consul
      service:
        name: consul
        enabled: true
        state: started
