all:
  hosts:
    consul:
      ansible_host: 54.151.172.68
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
    consul1:
      ansible_host: 54.169.201.105
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
  children:
    consul_cluster:
      hosts:
        consul:
        consul1:
