all:
  hosts:
    consul:
      ansible_host: 54.254.175.136
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
    consul1:
      ansible_host: 54.151.180.89
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
  children:
    consul_cluster:
      hosts:
        consul:
        consul1:
    consul_master:
      hosts:
        consul:
    consul_client:
      hosts:
        consul1:
